export const GET_VOCABULARY_SUCCESS = 'GET_VOCABULARY_SUCCESS';
export const GET_VOCABULARY_ERROR = 'GET_VOCABULARY_ERROR';
export const CHANGE_DESCRIPTION_SUCCESS = 'CHANGE_DESCRIPTION_SUCCESS';
export const CHANGE_DESCRIPTION_ERROR = 'CHANGE_DESCRIPTION_ERROR';